{
 "title": "Confluence dashboard",
 "description": "Shows Confluence JVM and usage metrics",
 "tags": [
  "JVM",
  "prometheus",
  "Atlassian"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(confluence_global_spaces_gauge,instance)"
   }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$Instance\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$Instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{instance=\"$Instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$Instance\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=\"$Instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Login/Logout",
   "type": "graph",
   "description": "Login/Logout increases per 1 hour",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(confluence_user_login_count{instance=\"$Instance\"}[1h]))",
     "legendFormat": "Login"
    },
    {
     "expr": "sum(increase(confluence_user_logout_count{instance=\"$Instance\"}[1h]))",
     "legendFormat": "Logout"
    }
   ]
  },
  {
   "title": "Mail Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluence_mail_queue_gauge{instance=\"$Instance\"}",
     "legendFormat": "queue"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(confluence_request_duration_on_path_sum{instance=\"$Instance\"}[1m])) by (path)) / (sum(rate(confluence_request_duration_on_path_count{instance=\"$Instance\"}[1m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Common Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Attachments",
   "type": "singlestat",
   "description": "Displays the current attachments size",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "confluence_total_attachment_size_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "The uptime of the Java virtual machine in milliseconds",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 25 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_uptime_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Pages",
   "type": "singlestat",
   "description": "The total pages",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_pages_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Blog-posts",
   "type": "singlestat",
   "description": "The total blog-posts",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_blogposts_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Global spaces",
   "type": "singlestat",
   "description": "The total global spaces",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_global_spaces_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Personal spaces",
   "type": "singlestat",
   "description": "The total personal spaces",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_personal_spaces_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Allowed users",
   "type": "singlestat",
   "description": "The maximum allowed users",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_allowed_users_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "singlestat",
   "description": "The current active users",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_active_users_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "1-hour sessions",
   "type": "singlestat",
   "description": "The total 1-hour active sessions",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_one_hour_active_users_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Today sessions",
   "type": "singlestat",
   "description": "The today active sessions",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_today_active_users_gauge{instance=\"$Instance\"}"
    }
   ]
  }
 ]
}