{
 "title": "Host Monitor",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Total Alerts",
   "type": "singlestat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "severity=\"critical\",",
     "labelSelector": " instance,app,type,env,job,summary",
     "legendFormat": "{{msg}}",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "severity=\"warning\"",
     "labelSelector": " instance,app,type,env,job,summary",
     "legendFormat": "{{msg}}",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$Instance\",type=\"node\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_uptime{instance=\"$Instance\",type=\"node\"}"
    }
   ]
  },
  {
   "title": "Host Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$Instance\",type=\"node\"}[1d])/count_over_time(up{instance=\"$Instance\",type=\"node\"}[1d])"
    }
   ]
  },
  {
   "title": "Host Loads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load5{instance=\"$Instance\",type=\"node\"}",
     "legendFormat": "{{instance}}: system_load5 "
    },
    {
     "expr": "system_load15{instance=\"$Instance\",type=\"node\"}",
     "legendFormat": " {{instance}}: system_load15"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 -(cpu_usage_idle{instance=~ \"$Instance\",cpu=\"cpu-total\",type=\"node\"} + cpu_usage_iowait{instance=~ \"$Instance\",cpu=\"cpu-total\",type=\"node\"}) ",
     "legendFormat": "{{instance}}: CPU usage"
    }
   ]
  },
  {
   "title": "Host Disk Usage(Used)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{instance=\"$Instance\",fstype!=\"rootfs\",type=\"node\"}",
     "legendFormat": "{{instance}}: {{path}}"
    }
   ]
  },
  {
   "title": "Host Memory Usage(used))",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{instance=\"$Instance\",type=\"node\"}",
     "legendFormat": "{{instance}}: Memory usage"
    }
   ]
  },
  {
   "title": "Network Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nstat_TcpCurrEstab{instance=\"$Instance\",type=\"node\"}",
     "legendFormat": "{{instance}}: Current Established Connection "
    },
    {
     "expr": "nstat_TcpActiveOpens{instance=\"$Instance\",type=\"node\"}",
     "legendFormat": "{{instance}}: Active Open Connections "
    },
    {
     "expr": "nstat_TcpAttemptFails{instance=\"$Instance\",type=\"node\"}",
     "legendFormat": "{{instance}}: Attemp Fails"
    },
    {
     "expr": "nstat_TcpEstabResets{instance=\"$Instance\",type=\"node\"}",
     "legendFormat": "{{instance}}: Connection resets"
    }
   ]
  }
 ]
}