{
 "title": "Jira Dashboard",
 "description": "Shows Jira JVM and usage metrics",
 "tags": [
  "prometheus",
  "Atlassian"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(jira_total_issues_gauge, instance)"
   }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$Instance\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$Instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{instance=\"$Instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$Instance\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=\"$Instance\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "JIRA Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Update Issues Per Project",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jira_issue_update_count{instance=\"$Instance\"}) by (projectKey)",
     "legendFormat": "{{projectKey}}"
    }
   ]
  },
  {
   "title": "Update Issues Per User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jira_issue_update_count{instance=\"$Instance\"}) by (username)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Login/Logout",
   "type": "graph",
   "description": "Login/Logout increases per 1 hour",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jira_user_login_count{instance=\"$Instance\"}[1h]))",
     "legendFormat": "Login"
    },
    {
     "expr": "sum(increase(jira_user_logout_count{instance=\"$Instance\"}[1h]))",
     "legendFormat": "Logout"
    }
   ]
  },
  {
   "title": "Dashboards Views",
   "type": "graph",
   "description": "Views of all dashboards increases",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jira_dashboard_view_count{instance=\"$Instance\"}[1h]))"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(jira_request_duration_on_path_sum{instance=\"$Instance\"}[1m])) by (path)) / (sum(rate(jira_request_duration_on_path_count{instance=\"$Instance\"}[1m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Common Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Attachments",
   "type": "singlestat",
   "description": "Displays the current attachments size",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_total_attachment_size_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "The uptime of the Java virtual machine in milliseconds",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_uptime_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Total Issues",
   "type": "singlestat",
   "description": "The total issues in JIRA",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_total_issues_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "All Users",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_all_users_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_active_users_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_total_sessions_gauge{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Authorized  Sessions",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_authorized_sessions_gauge{instance=\"$Instance\"}"
    }
   ]
  }
 ]
}